redis:
  host:
    - "172.21.211.214:9531"
  user: ""
  pwd: ""
mysql:
  player:
    host: "172.21.211.214"
    user: "root"
    port: 3366
    password: "yxh2362023!@#"
    database: "fg_player"
  manager:
    host: "172.21.211.214"
    user: "root"
    port: 3366
    password: "yxh2362023!@#"
    database: "fg_web_manager"
elastic:
  hosts:
    - "http://172.21.211.214:9200"
  username: "elastic"
  password: "000000"
#鏃ュ織淇濆瓨璺緞
log: ""
