// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: datacenter.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimeOut       int64                  `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionReq) Reset() {
	*x = GetSessionReq{}
	mi := &file_datacenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionReq) ProtoMessage() {}

func (x *GetSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionReq.ProtoReflect.Descriptor instead.
func (*GetSessionReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetSessionReq) GetTimeOut() int64 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type GetSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResp) Reset() {
	*x = GetSessionResp{}
	mi := &file_datacenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResp) ProtoMessage() {}

func (x *GetSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResp.ProtoReflect.Descriptor instead.
func (*GetSessionResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetSessionResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetGameListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListReq) Reset() {
	*x = GetGameListReq{}
	mi := &file_datacenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReq) ProtoMessage() {}

func (x *GetGameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReq.ProtoReflect.Descriptor instead.
func (*GetGameListReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{2}
}

type GetGameListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	// 热门游戏的symbol
	Hot []string `protobuf:"bytes,2,rep,name=hot,proto3" json:"hot,omitempty"`
	// 新游戏
	New []string `protobuf:"bytes,3,rep,name=new,proto3" json:"new,omitempty"`
	// 推荐游戏
	Recommend []string `protobuf:"bytes,4,rep,name=recommend,proto3" json:"recommend,omitempty"`
	// 所有游戏及状态
	All           []*GetGameListResp_GameInfoItem `protobuf:"bytes,5,rep,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResp) Reset() {
	*x = GetGameListResp{}
	mi := &file_datacenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResp) ProtoMessage() {}

func (x *GetGameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResp.ProtoReflect.Descriptor instead.
func (*GetGameListResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameListResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetGameListResp) GetHot() []string {
	if x != nil {
		return x.Hot
	}
	return nil
}

func (x *GetGameListResp) GetNew() []string {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *GetGameListResp) GetRecommend() []string {
	if x != nil {
		return x.Recommend
	}
	return nil
}

func (x *GetGameListResp) GetAll() []*GetGameListResp_GameInfoItem {
	if x != nil {
		return x.All
	}
	return nil
}

type UserLockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockReq) Reset() {
	*x = UserLockReq{}
	mi := &file_datacenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockReq) ProtoMessage() {}

func (x *UserLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockReq.ProtoReflect.Descriptor instead.
func (*UserLockReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{4}
}

func (x *UserLockReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserLockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockResp) Reset() {
	*x = UserLockResp{}
	mi := &file_datacenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockResp) ProtoMessage() {}

func (x *UserLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockResp.ProtoReflect.Descriptor instead.
func (*UserLockResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{5}
}

func (x *UserLockResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserUnLockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnLockReq) Reset() {
	*x = UserUnLockReq{}
	mi := &file_datacenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnLockReq) ProtoMessage() {}

func (x *UserUnLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnLockReq.ProtoReflect.Descriptor instead.
func (*UserUnLockReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{6}
}

func (x *UserUnLockReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserUnLockReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserUnLockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnLockResp) Reset() {
	*x = UserUnLockResp{}
	mi := &file_datacenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnLockResp) ProtoMessage() {}

func (x *UserUnLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnLockResp.ProtoReflect.Descriptor instead.
func (*UserUnLockResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{7}
}

func (x *UserUnLockResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetRecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"` //hash不为空，则以hash为准忽略其他参数（兼容旧调用）
	Currency      string                 `protobuf:"bytes,4,opt,name=Currency,proto3" json:"Currency,omitempty"`
	GameId        uint32                 `protobuf:"varint,5,opt,name=GameId,proto3" json:"GameId,omitempty"`       // 可转 symbol；与 Symbol 二选一
	StartTime     int64                  `protobuf:"varint,6,opt,name=StartTime,proto3" json:"StartTime,omitempty"` // playedDate 起始（毫秒），0 表示不限
	EndTime       int64                  `protobuf:"varint,7,opt,name=EndTime,proto3" json:"EndTime,omitempty"`     // playedDate 结束（毫秒），0 表示不限
	Page          int32                  `protobuf:"varint,8,opt,name=Page,proto3" json:"Page,omitempty"`           // 从 1 开始，默认 1
	Size          int32                  `protobuf:"varint,9,opt,name=Size,proto3" json:"Size,omitempty"`           // 默认 20，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsReq) Reset() {
	*x = GetRecordsReq{}
	mi := &file_datacenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsReq) ProtoMessage() {}

func (x *GetRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsReq.ProtoReflect.Descriptor instead.
func (*GetRecordsReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{8}
}

func (x *GetRecordsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecordsReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetRecordsReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetRecordsReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRecordsReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetRecordsReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetRecordsReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetRecordsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecordsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RecordItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        uint32                 `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"` //代理id
	UserId         uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`   //玩家id
	Bet            float64                `protobuf:"fixed64,3,opt,name=bet,proto3" json:"bet,omitempty"`        //有效下注
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,5,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	BaseBet        float64                `protobuf:"fixed64,6,opt,name=base_bet,json=baseBet,proto3" json:"base_bet,omitempty"`
	Win            float64                `protobuf:"fixed64,7,opt,name=win,proto3" json:"win,omitempty"`
	Rtp            float64                `protobuf:"fixed64,8,opt,name=rtp,proto3" json:"rtp,omitempty"`
	PlayedDate     int64                  `protobuf:"varint,9,opt,name=playedDate,proto3" json:"playedDate,omitempty"`
	RoundID        string                 `protobuf:"bytes,10,opt,name=roundID,proto3" json:"roundID,omitempty"`
	Init           string                 `protobuf:"bytes,11,opt,name=init,proto3" json:"init,omitempty"`
	Log            []*RecordLog           `protobuf:"bytes,12,rep,name=log,proto3" json:"log,omitempty"`       //详细
	Symbol         string                 `protobuf:"bytes,13,opt,name=symbol,proto3" json:"symbol,omitempty"` //游戏id
	Balance        float64                `protobuf:"fixed64,14,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceCash    float64                `protobuf:"fixed64,15,opt,name=balance_cash,json=balanceCash,proto3" json:"balance_cash,omitempty"`
	BalanceBonus   float64                `protobuf:"fixed64,16,opt,name=balance_bonus,json=balanceBonus,proto3" json:"balance_bonus,omitempty"`
	Hash           string                 `protobuf:"bytes,17,opt,name=hash,proto3" json:"hash,omitempty"`
	GameId         uint32                 `protobuf:"varint,18,opt,name=gameId,proto3" json:"gameId,omitempty"`
	GameName       string                 `protobuf:"bytes,19,opt,name=gameName,proto3" json:"gameName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordItem) Reset() {
	*x = RecordItem{}
	mi := &file_datacenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordItem) ProtoMessage() {}

func (x *RecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordItem.ProtoReflect.Descriptor instead.
func (*RecordItem) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{9}
}

func (x *RecordItem) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RecordItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordItem) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *RecordItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordItem) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *RecordItem) GetBaseBet() float64 {
	if x != nil {
		return x.BaseBet
	}
	return 0
}

func (x *RecordItem) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *RecordItem) GetRtp() float64 {
	if x != nil {
		return x.Rtp
	}
	return 0
}

func (x *RecordItem) GetPlayedDate() int64 {
	if x != nil {
		return x.PlayedDate
	}
	return 0
}

func (x *RecordItem) GetRoundID() string {
	if x != nil {
		return x.RoundID
	}
	return ""
}

func (x *RecordItem) GetInit() string {
	if x != nil {
		return x.Init
	}
	return ""
}

func (x *RecordItem) GetLog() []*RecordLog {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *RecordItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RecordItem) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *RecordItem) GetBalanceCash() float64 {
	if x != nil {
		return x.BalanceCash
	}
	return 0
}

func (x *RecordItem) GetBalanceBonus() float64 {
	if x != nil {
		return x.BalanceBonus
	}
	return 0
}

func (x *RecordItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RecordItem) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RecordItem) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

type GetRecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Data          []*RecordItem          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsResp) Reset() {
	*x = GetRecordsResp{}
	mi := &file_datacenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResp) ProtoMessage() {}

func (x *GetRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResp.ProtoReflect.Descriptor instead.
func (*GetRecordsResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecordsResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetRecordsResp) GetData() []*RecordItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetRecordsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRecordDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=recordId,proto3" json:"recordId,omitempty"` // hash 或 roundID
	UserId        uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GameId        uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordDetailReq) Reset() {
	*x = GetRecordDetailReq{}
	mi := &file_datacenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordDetailReq) ProtoMessage() {}

func (x *GetRecordDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordDetailReq.ProtoReflect.Descriptor instead.
func (*GetRecordDetailReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecordDetailReq) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *GetRecordDetailReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecordDetailReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetRecordDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Data          *RecordItem            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordDetailResp) Reset() {
	*x = GetRecordDetailResp{}
	mi := &file_datacenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordDetailResp) ProtoMessage() {}

func (x *GetRecordDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordDetailResp.ProtoReflect.Descriptor instead.
func (*GetRecordDetailResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecordDetailResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetRecordDetailResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetRecordDetailResp) GetData() *RecordItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecordLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cr            string                 `protobuf:"bytes,1,opt,name=cr,proto3" json:"cr,omitempty"`
	Sr            string                 `protobuf:"bytes,2,opt,name=sr,proto3" json:"sr,omitempty"`
	RoundId       string                 `protobuf:"bytes,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLog) Reset() {
	*x = RecordLog{}
	mi := &file_datacenter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLog) ProtoMessage() {}

func (x *RecordLog) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLog.ProtoReflect.Descriptor instead.
func (*RecordLog) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{13}
}

func (x *RecordLog) GetCr() string {
	if x != nil {
		return x.Cr
	}
	return ""
}

func (x *RecordLog) GetSr() string {
	if x != nil {
		return x.Sr
	}
	return ""
}

func (x *RecordLog) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type GetPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Factory       uint32                 `protobuf:"varint,2,opt,name=Factory,proto3" json:"Factory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerReq) Reset() {
	*x = GetPlayerReq{}
	mi := &file_datacenter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReq) ProtoMessage() {}

func (x *GetPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReq.ProtoReflect.Descriptor instead.
func (*GetPlayerReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{14}
}

func (x *GetPlayerReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GetPlayerReq) GetFactory() uint32 {
	if x != nil {
		return x.Factory
	}
	return 0
}

type GetPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HumanPlayer   *HumanPlayer           `protobuf:"bytes,1,opt,name=HumanPlayer,proto3" json:"HumanPlayer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResp) Reset() {
	*x = GetPlayerResp{}
	mi := &file_datacenter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResp) ProtoMessage() {}

func (x *GetPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResp.ProtoReflect.Descriptor instead.
func (*GetPlayerResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{15}
}

func (x *GetPlayerResp) GetHumanPlayer() *HumanPlayer {
	if x != nil {
		return x.HumanPlayer
	}
	return nil
}

type GetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimeOut       int64                  `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueReq) Reset() {
	*x = GetValueReq{}
	mi := &file_datacenter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueReq) ProtoMessage() {}

func (x *GetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueReq.ProtoReflect.Descriptor instead.
func (*GetValueReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{16}
}

func (x *GetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetValueReq) GetTimeOut() int64 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type GetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResp) Reset() {
	*x = GetValueResp{}
	mi := &file_datacenter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResp) ProtoMessage() {}

func (x *GetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResp.ProtoReflect.Descriptor instead.
func (*GetValueResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{17}
}

func (x *GetValueResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetValueResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeOut       int32                  `protobuf:"varint,3,opt,name=time_out,json=timeOut,proto3" json:"time_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueReq) Reset() {
	*x = SetValueReq{}
	mi := &file_datacenter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueReq) ProtoMessage() {}

func (x *SetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueReq.ProtoReflect.Descriptor instead.
func (*SetValueReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{18}
}

func (x *SetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueReq) GetTimeOut() int32 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

type SetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResp) Reset() {
	*x = SetValueResp{}
	mi := &file_datacenter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResp) ProtoMessage() {}

func (x *SetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResp.ProtoReflect.Descriptor instead.
func (*SetValueResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{19}
}

func (x *SetValueResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type UpdatePlayerAvatarAndGenderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender        uint32                 `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Factory       uint32                 `protobuf:"varint,4,opt,name=Factory,proto3" json:"Factory,omitempty"`
	HeadFrame     string                 `protobuf:"bytes,5,opt,name=head_frame,json=headFrame,proto3" json:"head_frame,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"` //昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerAvatarAndGenderReq) Reset() {
	*x = UpdatePlayerAvatarAndGenderReq{}
	mi := &file_datacenter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerAvatarAndGenderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerAvatarAndGenderReq) ProtoMessage() {}

func (x *UpdatePlayerAvatarAndGenderReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerAvatarAndGenderReq.ProtoReflect.Descriptor instead.
func (*UpdatePlayerAvatarAndGenderReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePlayerAvatarAndGenderReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdatePlayerAvatarAndGenderReq) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetFactory() uint32 {
	if x != nil {
		return x.Factory
	}
	return 0
}

func (x *UpdatePlayerAvatarAndGenderReq) GetHeadFrame() string {
	if x != nil {
		return x.HeadFrame
	}
	return ""
}

func (x *UpdatePlayerAvatarAndGenderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePlayerAvatarAndGenderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerAvatarAndGenderResp) Reset() {
	*x = UpdatePlayerAvatarAndGenderResp{}
	mi := &file_datacenter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerAvatarAndGenderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerAvatarAndGenderResp) ProtoMessage() {}

func (x *UpdatePlayerAvatarAndGenderResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerAvatarAndGenderResp.ProtoReflect.Descriptor instead.
func (*UpdatePlayerAvatarAndGenderResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{21}
}

type AuthenticateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	GameId        uint32                 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	EntryUserId   uint32                 `protobuf:"varint,3,opt,name=entryUserId,proto3" json:"entryUserId,omitempty"` // 可选，>0 时必须与 session 用户一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_datacenter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{22}
}

func (x *AuthenticateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *AuthenticateReq) GetEntryUserId() uint32 {
	if x != nil {
		return x.EntryUserId
	}
	return 0
}

type AuthenticateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	IsReEnter     bool                   `protobuf:"varint,3,opt,name=isReEnter,proto3" json:"isReEnter,omitempty"`
	AttemptCount  int64                  `protobuf:"varint,4,opt,name=attemptCount,proto3" json:"attemptCount,omitempty"`
	UserId        uint32                 `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResp) Reset() {
	*x = AuthenticateResp{}
	mi := &file_datacenter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResp) ProtoMessage() {}

func (x *AuthenticateResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResp.ProtoReflect.Descriptor instead.
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{23}
}

func (x *AuthenticateResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *AuthenticateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResp) GetIsReEnter() bool {
	if x != nil {
		return x.IsReEnter
	}
	return false
}

func (x *AuthenticateResp) GetAttemptCount() int64 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *AuthenticateResp) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthenticateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLoginDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginDataReq) Reset() {
	*x = GetLoginDataReq{}
	mi := &file_datacenter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginDataReq) ProtoMessage() {}

func (x *GetLoginDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginDataReq.ProtoReflect.Descriptor instead.
func (*GetLoginDataReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{24}
}

func (x *GetLoginDataReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginCurrency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyId    uint32                 `protobuf:"varint,1,opt,name=currencyId,proto3" json:"currencyId,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CurrencyRate  float64                `protobuf:"fixed64,3,opt,name=currencyRate,proto3" json:"currencyRate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCurrency) Reset() {
	*x = LoginCurrency{}
	mi := &file_datacenter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCurrency) ProtoMessage() {}

func (x *LoginCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCurrency.ProtoReflect.Descriptor instead.
func (*LoginCurrency) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{25}
}

func (x *LoginCurrency) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *LoginCurrency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LoginCurrency) GetCurrencyRate() float64 {
	if x != nil {
		return x.CurrencyRate
	}
	return 0
}

type LoginProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AgentId       uint32                 `protobuf:"varint,3,opt,name=agentId,proto3" json:"agentId,omitempty"`
	TopAgentId    uint32                 `protobuf:"varint,4,opt,name=topAgentId,proto3" json:"topAgentId,omitempty"`
	UserIcon      int32                  `protobuf:"varint,5,opt,name=userIcon,proto3" json:"userIcon,omitempty"`
	LoginType     int32                  `protobuf:"varint,6,opt,name=loginType,proto3" json:"loginType,omitempty"`
	Gm            int32                  `protobuf:"varint,7,opt,name=gm,proto3" json:"gm,omitempty"`
	Rate          float64                `protobuf:"fixed64,8,opt,name=rate,proto3" json:"rate,omitempty"`
	Currency      *LoginCurrency         `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProfile) Reset() {
	*x = LoginProfile{}
	mi := &file_datacenter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProfile) ProtoMessage() {}

func (x *LoginProfile) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProfile.ProtoReflect.Descriptor instead.
func (*LoginProfile) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{26}
}

func (x *LoginProfile) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginProfile) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginProfile) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *LoginProfile) GetTopAgentId() uint32 {
	if x != nil {
		return x.TopAgentId
	}
	return 0
}

func (x *LoginProfile) GetUserIcon() int32 {
	if x != nil {
		return x.UserIcon
	}
	return 0
}

func (x *LoginProfile) GetLoginType() int32 {
	if x != nil {
		return x.LoginType
	}
	return 0
}

func (x *LoginProfile) GetGm() int32 {
	if x != nil {
		return x.Gm
	}
	return 0
}

func (x *LoginProfile) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LoginProfile) GetCurrency() *LoginCurrency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type GetLoginDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Profile       *LoginProfile          `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginDataResp) Reset() {
	*x = GetLoginDataResp{}
	mi := &file_datacenter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginDataResp) ProtoMessage() {}

func (x *GetLoginDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginDataResp.ProtoReflect.Descriptor instead.
func (*GetLoginDataResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{27}
}

func (x *GetLoginDataResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetLoginDataResp) GetProfile() *LoginProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_datacenter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{28}
}

func (x *ValidateTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_datacenter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{29}
}

func (x *ValidateTokenResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *ValidateTokenResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GetGameListResp_GameInfoItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏标志
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 游戏状态 1 正常 2 维护
	State         int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameListResp_GameInfoItem) Reset() {
	*x = GetGameListResp_GameInfoItem{}
	mi := &file_datacenter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameListResp_GameInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResp_GameInfoItem) ProtoMessage() {}

func (x *GetGameListResp_GameInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_datacenter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResp_GameInfoItem.ProtoReflect.Descriptor instead.
func (*GetGameListResp_GameInfoItem) Descriptor() ([]byte, []int) {
	return file_datacenter_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetGameListResp_GameInfoItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetGameListResp_GameInfoItem) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_datacenter_proto protoreflect.FileDescriptor

const file_datacenter_proto_rawDesc = "" +
	"\n" +
	"\x10datacenter.proto\x12\n" +
	"datacenter\x1a\fplayer.proto\x1a\n" +
	"base.proto\";\n" +
	"\rGetSessionReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\atimeOut\x18\x02 \x01(\x03R\atimeOut\"L\n" +
	"\x0eGetSessionResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x10\n" +
	"\x0eGetGameListReq\"\xf3\x01\n" +
	"\x0fGetGameListResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03hot\x18\x02 \x03(\tR\x03hot\x12\x10\n" +
	"\x03new\x18\x03 \x03(\tR\x03new\x12\x1c\n" +
	"\trecommend\x18\x04 \x03(\tR\trecommend\x12:\n" +
	"\x03all\x18\x05 \x03(\v2(.datacenter.GetGameListResp.GameInfoItemR\x03all\x1a<\n" +
	"\fGameInfoItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\"%\n" +
	"\vUserLockReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"&\n" +
	"\fUserLockResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"=\n" +
	"\rUserUnLockReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"(\n" +
	"\x0eUserUnLockResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\xe7\x01\n" +
	"\rGetRecordsReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x12\n" +
	"\x04Hash\x18\x03 \x01(\tR\x04Hash\x12\x1a\n" +
	"\bCurrency\x18\x04 \x01(\tR\bCurrency\x12\x16\n" +
	"\x06GameId\x18\x05 \x01(\rR\x06GameId\x12\x1c\n" +
	"\tStartTime\x18\x06 \x01(\x03R\tStartTime\x12\x18\n" +
	"\aEndTime\x18\a \x01(\x03R\aEndTime\x12\x12\n" +
	"\x04Page\x18\b \x01(\x05R\x04Page\x12\x12\n" +
	"\x04Size\x18\t \x01(\x05R\x04Size\"\x8c\x04\n" +
	"\n" +
	"RecordItem\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\rR\aagentId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\x10\n" +
	"\x03bet\x18\x03 \x01(\x01R\x03bet\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12&\n" +
	"\x0ecurrencySymbol\x18\x05 \x01(\tR\x0ecurrencySymbol\x12\x19\n" +
	"\bbase_bet\x18\x06 \x01(\x01R\abaseBet\x12\x10\n" +
	"\x03win\x18\a \x01(\x01R\x03win\x12\x10\n" +
	"\x03rtp\x18\b \x01(\x01R\x03rtp\x12\x1e\n" +
	"\n" +
	"playedDate\x18\t \x01(\x03R\n" +
	"playedDate\x12\x18\n" +
	"\aroundID\x18\n" +
	" \x01(\tR\aroundID\x12\x12\n" +
	"\x04init\x18\v \x01(\tR\x04init\x12'\n" +
	"\x03log\x18\f \x03(\v2\x15.datacenter.RecordLogR\x03log\x12\x16\n" +
	"\x06symbol\x18\r \x01(\tR\x06symbol\x12\x18\n" +
	"\abalance\x18\x0e \x01(\x01R\abalance\x12!\n" +
	"\fbalance_cash\x18\x0f \x01(\x01R\vbalanceCash\x12#\n" +
	"\rbalance_bonus\x18\x10 \x01(\x01R\fbalanceBonus\x12\x12\n" +
	"\x04hash\x18\x11 \x01(\tR\x04hash\x12\x16\n" +
	"\x06gameId\x18\x12 \x01(\rR\x06gameId\x12\x1a\n" +
	"\bgameName\x18\x13 \x01(\tR\bgameName\"x\n" +
	"\x0eGetRecordsResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.datacenter.RecordItemR\x04data\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"`\n" +
	"\x12GetRecordDetailReq\x12\x1a\n" +
	"\brecordId\x18\x01 \x01(\tR\brecordId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\"}\n" +
	"\x13GetRecordDetailResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.datacenter.RecordItemR\x04data\"E\n" +
	"\tRecordLog\x12\x0e\n" +
	"\x02cr\x18\x01 \x01(\tR\x02cr\x12\x0e\n" +
	"\x02sr\x18\x02 \x01(\tR\x02sr\x12\x18\n" +
	"\aroundId\x18\x03 \x01(\tR\aroundId\"D\n" +
	"\fGetPlayerReq\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\rR\bPlayerId\x12\x18\n" +
	"\aFactory\x18\x02 \x01(\rR\aFactory\"F\n" +
	"\rGetPlayerResp\x125\n" +
	"\vHumanPlayer\x18\x01 \x01(\v2\x13.player.HumanPlayerR\vHumanPlayer\"9\n" +
	"\vGetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\atimeOut\x18\x02 \x01(\x03R\atimeOut\"J\n" +
	"\fGetValueResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"P\n" +
	"\vSetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\btime_out\x18\x03 \x01(\x05R\atimeOut\"4\n" +
	"\fSetValueResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"\xb9\x01\n" +
	"\x1eUpdatePlayerAvatarAndGenderReq\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\rR\bPlayerId\x12\x16\n" +
	"\x06Avatar\x18\x02 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\x03 \x01(\rR\x06Gender\x12\x18\n" +
	"\aFactory\x18\x04 \x01(\rR\aFactory\x12\x1d\n" +
	"\n" +
	"head_frame\x18\x05 \x01(\tR\theadFrame\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"!\n" +
	"\x1fUpdatePlayerAvatarAndGenderResp\"a\n" +
	"\x0fAuthenticateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\rR\x06gameId\x12 \n" +
	"\ventryUserId\x18\x03 \x01(\rR\ventryUserId\"\xc6\x01\n" +
	"\x10AuthenticateResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\tisReEnter\x18\x03 \x01(\bR\tisReEnter\x12\"\n" +
	"\fattemptCount\x18\x04 \x01(\x03R\fattemptCount\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\rR\x06userId\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\")\n" +
	"\x0fGetLoginDataReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"k\n" +
	"\rLoginCurrency\x12\x1e\n" +
	"\n" +
	"currencyId\x18\x01 \x01(\rR\n" +
	"currencyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\"\n" +
	"\fcurrencyRate\x18\x03 \x01(\x01R\fcurrencyRate\"\x91\x02\n" +
	"\fLoginProfile\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x18\n" +
	"\aagentId\x18\x03 \x01(\rR\aagentId\x12\x1e\n" +
	"\n" +
	"topAgentId\x18\x04 \x01(\rR\n" +
	"topAgentId\x12\x1a\n" +
	"\buserIcon\x18\x05 \x01(\x05R\buserIcon\x12\x1c\n" +
	"\tloginType\x18\x06 \x01(\x05R\tloginType\x12\x0e\n" +
	"\x02gm\x18\a \x01(\x05R\x02gm\x12\x12\n" +
	"\x04rate\x18\b \x01(\x01R\x04rate\x125\n" +
	"\bcurrency\x18\t \x01(\v2\x19.datacenter.LoginCurrencyR\bcurrency\"l\n" +
	"\x10GetLoginDataResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x122\n" +
	"\aprofile\x18\x02 \x01(\v2\x18.datacenter.LoginProfileR\aprofile\"@\n" +
	"\x10ValidateTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\"O\n" +
	"\x11ValidateTokenResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid2\xd8\a\n" +
	"\x11DataCenterService\x12@\n" +
	"\tGetPlayer\x12\x18.datacenter.GetPlayerReq\x1a\x19.datacenter.GetPlayerResp\x12=\n" +
	"\bGetValue\x12\x17.datacenter.GetValueReq\x1a\x18.datacenter.GetValueResp\x12=\n" +
	"\bSetValue\x12\x17.datacenter.SetValueReq\x1a\x18.datacenter.SetValueResp\x12v\n" +
	"\x1bUpdatePlayerAvatarAndGender\x12*.datacenter.UpdatePlayerAvatarAndGenderReq\x1a+.datacenter.UpdatePlayerAvatarAndGenderResp\x12C\n" +
	"\n" +
	"GetRecords\x12\x19.datacenter.GetRecordsReq\x1a\x1a.datacenter.GetRecordsResp\x12R\n" +
	"\x0fGetRecordDetail\x12\x1e.datacenter.GetRecordDetailReq\x1a\x1f.datacenter.GetRecordDetailResp\x12F\n" +
	"\vGetGameList\x12\x1a.datacenter.GetGameListReq\x1a\x1b.datacenter.GetGameListResp\x12=\n" +
	"\bUserLock\x12\x17.datacenter.UserLockReq\x1a\x18.datacenter.UserLockResp\x12C\n" +
	"\n" +
	"UserUnLock\x12\x19.datacenter.UserUnLockReq\x1a\x1a.datacenter.UserUnLockResp\x12B\n" +
	"\tGetSesson\x12\x19.datacenter.GetSessionReq\x1a\x1a.datacenter.GetSessionResp\x12I\n" +
	"\fAuthenticate\x12\x1b.datacenter.AuthenticateReq\x1a\x1c.datacenter.AuthenticateResp\x12I\n" +
	"\fGetLoginData\x12\x1b.datacenter.GetLoginDataReq\x1a\x1c.datacenter.GetLoginDataResp\x12L\n" +
	"\rValidateToken\x12\x1c.datacenter.ValidateTokenReq\x1a\x1d.datacenter.ValidateTokenRespB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_datacenter_proto_rawDescOnce sync.Once
	file_datacenter_proto_rawDescData []byte
)

func file_datacenter_proto_rawDescGZIP() []byte {
	file_datacenter_proto_rawDescOnce.Do(func() {
		file_datacenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datacenter_proto_rawDesc), len(file_datacenter_proto_rawDesc)))
	})
	return file_datacenter_proto_rawDescData
}

var file_datacenter_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_datacenter_proto_goTypes = []any{
	(*GetSessionReq)(nil),                   // 0: datacenter.GetSessionReq
	(*GetSessionResp)(nil),                  // 1: datacenter.GetSessionResp
	(*GetGameListReq)(nil),                  // 2: datacenter.GetGameListReq
	(*GetGameListResp)(nil),                 // 3: datacenter.GetGameListResp
	(*UserLockReq)(nil),                     // 4: datacenter.UserLockReq
	(*UserLockResp)(nil),                    // 5: datacenter.UserLockResp
	(*UserUnLockReq)(nil),                   // 6: datacenter.UserUnLockReq
	(*UserUnLockResp)(nil),                  // 7: datacenter.UserUnLockResp
	(*GetRecordsReq)(nil),                   // 8: datacenter.GetRecordsReq
	(*RecordItem)(nil),                      // 9: datacenter.RecordItem
	(*GetRecordsResp)(nil),                  // 10: datacenter.GetRecordsResp
	(*GetRecordDetailReq)(nil),              // 11: datacenter.GetRecordDetailReq
	(*GetRecordDetailResp)(nil),             // 12: datacenter.GetRecordDetailResp
	(*RecordLog)(nil),                       // 13: datacenter.RecordLog
	(*GetPlayerReq)(nil),                    // 14: datacenter.GetPlayerReq
	(*GetPlayerResp)(nil),                   // 15: datacenter.GetPlayerResp
	(*GetValueReq)(nil),                     // 16: datacenter.GetValueReq
	(*GetValueResp)(nil),                    // 17: datacenter.GetValueResp
	(*SetValueReq)(nil),                     // 18: datacenter.SetValueReq
	(*SetValueResp)(nil),                    // 19: datacenter.SetValueResp
	(*UpdatePlayerAvatarAndGenderReq)(nil),  // 20: datacenter.UpdatePlayerAvatarAndGenderReq
	(*UpdatePlayerAvatarAndGenderResp)(nil), // 21: datacenter.UpdatePlayerAvatarAndGenderResp
	(*AuthenticateReq)(nil),                 // 22: datacenter.AuthenticateReq
	(*AuthenticateResp)(nil),                // 23: datacenter.AuthenticateResp
	(*GetLoginDataReq)(nil),                 // 24: datacenter.GetLoginDataReq
	(*LoginCurrency)(nil),                   // 25: datacenter.LoginCurrency
	(*LoginProfile)(nil),                    // 26: datacenter.LoginProfile
	(*GetLoginDataResp)(nil),                // 27: datacenter.GetLoginDataResp
	(*ValidateTokenReq)(nil),                // 28: datacenter.ValidateTokenReq
	(*ValidateTokenResp)(nil),               // 29: datacenter.ValidateTokenResp
	(*GetGameListResp_GameInfoItem)(nil),    // 30: datacenter.GetGameListResp.GameInfoItem
	(ErrorCode)(0),                          // 31: base.error_code
	(*HumanPlayer)(nil),                     // 32: player.HumanPlayer
}
var file_datacenter_proto_depIdxs = []int32{
	31, // 0: datacenter.GetSessionResp.code:type_name -> base.error_code
	31, // 1: datacenter.GetGameListResp.code:type_name -> base.error_code
	30, // 2: datacenter.GetGameListResp.all:type_name -> datacenter.GetGameListResp.GameInfoItem
	13, // 3: datacenter.RecordItem.log:type_name -> datacenter.RecordLog
	31, // 4: datacenter.GetRecordsResp.code:type_name -> base.error_code
	9,  // 5: datacenter.GetRecordsResp.data:type_name -> datacenter.RecordItem
	31, // 6: datacenter.GetRecordDetailResp.code:type_name -> base.error_code
	9,  // 7: datacenter.GetRecordDetailResp.data:type_name -> datacenter.RecordItem
	32, // 8: datacenter.GetPlayerResp.HumanPlayer:type_name -> player.HumanPlayer
	31, // 9: datacenter.GetValueResp.code:type_name -> base.error_code
	31, // 10: datacenter.SetValueResp.code:type_name -> base.error_code
	31, // 11: datacenter.AuthenticateResp.code:type_name -> base.error_code
	25, // 12: datacenter.LoginProfile.currency:type_name -> datacenter.LoginCurrency
	31, // 13: datacenter.GetLoginDataResp.code:type_name -> base.error_code
	26, // 14: datacenter.GetLoginDataResp.profile:type_name -> datacenter.LoginProfile
	31, // 15: datacenter.ValidateTokenResp.code:type_name -> base.error_code
	14, // 16: datacenter.DataCenterService.GetPlayer:input_type -> datacenter.GetPlayerReq
	16, // 17: datacenter.DataCenterService.GetValue:input_type -> datacenter.GetValueReq
	18, // 18: datacenter.DataCenterService.SetValue:input_type -> datacenter.SetValueReq
	20, // 19: datacenter.DataCenterService.UpdatePlayerAvatarAndGender:input_type -> datacenter.UpdatePlayerAvatarAndGenderReq
	8,  // 20: datacenter.DataCenterService.GetRecords:input_type -> datacenter.GetRecordsReq
	11, // 21: datacenter.DataCenterService.GetRecordDetail:input_type -> datacenter.GetRecordDetailReq
	2,  // 22: datacenter.DataCenterService.GetGameList:input_type -> datacenter.GetGameListReq
	4,  // 23: datacenter.DataCenterService.UserLock:input_type -> datacenter.UserLockReq
	6,  // 24: datacenter.DataCenterService.UserUnLock:input_type -> datacenter.UserUnLockReq
	0,  // 25: datacenter.DataCenterService.GetSesson:input_type -> datacenter.GetSessionReq
	22, // 26: datacenter.DataCenterService.Authenticate:input_type -> datacenter.AuthenticateReq
	24, // 27: datacenter.DataCenterService.GetLoginData:input_type -> datacenter.GetLoginDataReq
	28, // 28: datacenter.DataCenterService.ValidateToken:input_type -> datacenter.ValidateTokenReq
	15, // 29: datacenter.DataCenterService.GetPlayer:output_type -> datacenter.GetPlayerResp
	17, // 30: datacenter.DataCenterService.GetValue:output_type -> datacenter.GetValueResp
	19, // 31: datacenter.DataCenterService.SetValue:output_type -> datacenter.SetValueResp
	21, // 32: datacenter.DataCenterService.UpdatePlayerAvatarAndGender:output_type -> datacenter.UpdatePlayerAvatarAndGenderResp
	10, // 33: datacenter.DataCenterService.GetRecords:output_type -> datacenter.GetRecordsResp
	12, // 34: datacenter.DataCenterService.GetRecordDetail:output_type -> datacenter.GetRecordDetailResp
	3,  // 35: datacenter.DataCenterService.GetGameList:output_type -> datacenter.GetGameListResp
	5,  // 36: datacenter.DataCenterService.UserLock:output_type -> datacenter.UserLockResp
	7,  // 37: datacenter.DataCenterService.UserUnLock:output_type -> datacenter.UserUnLockResp
	1,  // 38: datacenter.DataCenterService.GetSesson:output_type -> datacenter.GetSessionResp
	23, // 39: datacenter.DataCenterService.Authenticate:output_type -> datacenter.AuthenticateResp
	27, // 40: datacenter.DataCenterService.GetLoginData:output_type -> datacenter.GetLoginDataResp
	29, // 41: datacenter.DataCenterService.ValidateToken:output_type -> datacenter.ValidateTokenResp
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_datacenter_proto_init() }
func file_datacenter_proto_init() {
	if File_datacenter_proto != nil {
		return
	}
	file_player_proto_init()
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datacenter_proto_rawDesc), len(file_datacenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datacenter_proto_goTypes,
		DependencyIndexes: file_datacenter_proto_depIdxs,
		MessageInfos:      file_datacenter_proto_msgTypes,
	}.Build()
	File_datacenter_proto = out.File
	file_datacenter_proto_goTypes = nil
	file_datacenter_proto_depIdxs = nil
}
