// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: lottery.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolAmountResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint32                 `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId        uint32                 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAmountResultReq) Reset() {
	*x = PoolAmountResultReq{}
	mi := &file_lottery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAmountResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAmountResultReq) ProtoMessage() {}

func (x *PoolAmountResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAmountResultReq.ProtoReflect.Descriptor instead.
func (*PoolAmountResultReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *PoolAmountResultReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *PoolAmountResultReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PoolAmountResultReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

type PoolAmountResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAmountResultResp) Reset() {
	*x = PoolAmountResultResp{}
	mi := &file_lottery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAmountResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAmountResultResp) ProtoMessage() {}

func (x *PoolAmountResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAmountResultResp.ProtoReflect.Descriptor instead.
func (*PoolAmountResultResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *PoolAmountResultResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *PoolAmountResultResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceReq) Reset() {
	*x = GetBalanceReq{}
	mi := &file_lottery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceReq) ProtoMessage() {}

func (x *GetBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceReq.ProtoReflect.Descriptor instead.
func (*GetBalanceReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`          // 元，两位小数
	CurrencyCent  int64                  `protobuf:"varint,3,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"` // 分，权威整数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResp) Reset() {
	*x = GetBalanceResp{}
	mi := &file_lottery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResp) ProtoMessage() {}

func (x *GetBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResp.ProtoReflect.Descriptor instead.
func (*GetBalanceResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetBalanceResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResp) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

type SaveGameStorageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GameId         uint32                 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	StorageKey     string                 `protobuf:"bytes,4,opt,name=storageKey,proto3" json:"storageKey,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpireSeconds  int64                  `protobuf:"varint,6,opt,name=expireSeconds,proto3" json:"expireSeconds,omitempty"` // <=0 表示不过期
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveGameStorageReq) Reset() {
	*x = SaveGameStorageReq{}
	mi := &file_lottery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameStorageReq) ProtoMessage() {}

func (x *SaveGameStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameStorageReq.ProtoReflect.Descriptor instead.
func (*SaveGameStorageReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{4}
}

func (x *SaveGameStorageReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveGameStorageReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SaveGameStorageReq) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *SaveGameStorageReq) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *SaveGameStorageReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SaveGameStorageReq) GetExpireSeconds() int64 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type SaveGameStorageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameStorageResp) Reset() {
	*x = SaveGameStorageResp{}
	mi := &file_lottery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameStorageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameStorageResp) ProtoMessage() {}

func (x *SaveGameStorageResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameStorageResp.ProtoReflect.Descriptor instead.
func (*SaveGameStorageResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{5}
}

func (x *SaveGameStorageResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type LoadGameStorageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GameId         uint32                 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	StorageKey     string                 `protobuf:"bytes,4,opt,name=storageKey,proto3" json:"storageKey,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoadGameStorageReq) Reset() {
	*x = LoadGameStorageReq{}
	mi := &file_lottery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGameStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGameStorageReq) ProtoMessage() {}

func (x *LoadGameStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGameStorageReq.ProtoReflect.Descriptor instead.
func (*LoadGameStorageReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{6}
}

func (x *LoadGameStorageReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoadGameStorageReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *LoadGameStorageReq) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *LoadGameStorageReq) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type LoadGameStorageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGameStorageResp) Reset() {
	*x = LoadGameStorageResp{}
	mi := &file_lottery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGameStorageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGameStorageResp) ProtoMessage() {}

func (x *LoadGameStorageResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGameStorageResp.ProtoReflect.Descriptor instead.
func (*LoadGameStorageResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{7}
}

func (x *LoadGameStorageResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *LoadGameStorageResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LoadGameStorageResp) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DeleteGameStorageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GameId         uint32                 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	StorageKey     string                 `protobuf:"bytes,4,opt,name=storageKey,proto3" json:"storageKey,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteGameStorageReq) Reset() {
	*x = DeleteGameStorageReq{}
	mi := &file_lottery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameStorageReq) ProtoMessage() {}

func (x *DeleteGameStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameStorageReq.ProtoReflect.Descriptor instead.
func (*DeleteGameStorageReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGameStorageReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteGameStorageReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *DeleteGameStorageReq) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *DeleteGameStorageReq) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type DeleteGameStorageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameStorageResp) Reset() {
	*x = DeleteGameStorageResp{}
	mi := &file_lottery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameStorageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameStorageResp) ProtoMessage() {}

func (x *DeleteGameStorageResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameStorageResp.ProtoReflect.Descriptor instead.
func (*DeleteGameStorageResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGameStorageResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type GameStorageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageKey    string                 `protobuf:"bytes,1,opt,name=storageKey,proto3" json:"storageKey,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpireSeconds int64                  `protobuf:"varint,3,opt,name=expireSeconds,proto3" json:"expireSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStorageItem) Reset() {
	*x = GameStorageItem{}
	mi := &file_lottery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStorageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStorageItem) ProtoMessage() {}

func (x *GameStorageItem) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStorageItem.ProtoReflect.Descriptor instead.
func (*GameStorageItem) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{10}
}

func (x *GameStorageItem) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *GameStorageItem) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GameStorageItem) GetExpireSeconds() int64 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type SlotDoBetFlowControl struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RefundPoolAmount      string                 `protobuf:"bytes,1,opt,name=refundPoolAmount,proto3" json:"refundPoolAmount,omitempty"` // 未使用预占退回水池金额（元）
	DeleteGameStorageKeys []string               `protobuf:"bytes,2,rep,name=deleteGameStorageKeys,proto3" json:"deleteGameStorageKeys,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SlotDoBetFlowControl) Reset() {
	*x = SlotDoBetFlowControl{}
	mi := &file_lottery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotDoBetFlowControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotDoBetFlowControl) ProtoMessage() {}

func (x *SlotDoBetFlowControl) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotDoBetFlowControl.ProtoReflect.Descriptor instead.
func (*SlotDoBetFlowControl) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{11}
}

func (x *SlotDoBetFlowControl) GetRefundPoolAmount() string {
	if x != nil {
		return x.RefundPoolAmount
	}
	return ""
}

func (x *SlotDoBetFlowControl) GetDeleteGameStorageKeys() []string {
	if x != nil {
		return x.DeleteGameStorageKeys
	}
	return nil
}

type SlotsDoBetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId       uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId        uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	BetAmount     string                 `protobuf:"bytes,6,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	WinAmount     string                 `protobuf:"bytes,7,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
	PreWinAmount  string                 `protobuf:"bytes,8,opt,name=preWinAmount,proto3" json:"preWinAmount,omitempty"` // 预占最大赔付，对应 MaxProfitLoss
	Account       string                 `protobuf:"bytes,9,opt,name=account,proto3" json:"account,omitempty"`
	RecordJson    string                 `protobuf:"bytes,10,opt,name=recordJson,proto3" json:"recordJson,omitempty"` // UserRecordInfo JSON；同时作为注单 log
	GameStorage   []*GameStorageItem     `protobuf:"bytes,11,rep,name=gameStorage,proto3" json:"gameStorage,omitempty"`
	FlowControl   *SlotDoBetFlowControl  `protobuf:"bytes,12,opt,name=flowControl,proto3" json:"flowControl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsDoBetReq) Reset() {
	*x = SlotsDoBetReq{}
	mi := &file_lottery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsDoBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsDoBetReq) ProtoMessage() {}

func (x *SlotsDoBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsDoBetReq.ProtoReflect.Descriptor instead.
func (*SlotsDoBetReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{12}
}

func (x *SlotsDoBetReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SlotsDoBetReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SlotsDoBetReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SlotsDoBetReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *SlotsDoBetReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SlotsDoBetReq) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *SlotsDoBetReq) GetWinAmount() string {
	if x != nil {
		return x.WinAmount
	}
	return ""
}

func (x *SlotsDoBetReq) GetPreWinAmount() string {
	if x != nil {
		return x.PreWinAmount
	}
	return ""
}

func (x *SlotsDoBetReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SlotsDoBetReq) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

func (x *SlotsDoBetReq) GetGameStorage() []*GameStorageItem {
	if x != nil {
		return x.GameStorage
	}
	return nil
}

func (x *SlotsDoBetReq) GetFlowControl() *SlotDoBetFlowControl {
	if x != nil {
		return x.FlowControl
	}
	return nil
}

type SlotsDoBetFreeReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId        uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId         uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType   string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	RoundId        string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	WinAmount      string                 `protobuf:"bytes,6,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
	Account        string                 `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	RecordJson     string                 `protobuf:"bytes,8,opt,name=recordJson,proto3" json:"recordJson,omitempty"`         // 可空；纯状态 action 可不传注单
	TotalBetAmount string                 `protobuf:"bytes,9,opt,name=totalBetAmount,proto3" json:"totalBetAmount,omitempty"` // 原普通局下注，用于 Complete 统计
	Complete       bool                   `protobuf:"varint,10,opt,name=complete,proto3" json:"complete,omitempty"`
	GameStorage    []*GameStorageItem     `protobuf:"bytes,11,rep,name=gameStorage,proto3" json:"gameStorage,omitempty"`
	FlowControl    *SlotDoBetFlowControl  `protobuf:"bytes,12,opt,name=flowControl,proto3" json:"flowControl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlotsDoBetFreeReq) Reset() {
	*x = SlotsDoBetFreeReq{}
	mi := &file_lottery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsDoBetFreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsDoBetFreeReq) ProtoMessage() {}

func (x *SlotsDoBetFreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsDoBetFreeReq.ProtoReflect.Descriptor instead.
func (*SlotsDoBetFreeReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{13}
}

func (x *SlotsDoBetFreeReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SlotsDoBetFreeReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SlotsDoBetFreeReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SlotsDoBetFreeReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetWinAmount() string {
	if x != nil {
		return x.WinAmount
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetTotalBetAmount() string {
	if x != nil {
		return x.TotalBetAmount
	}
	return ""
}

func (x *SlotsDoBetFreeReq) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *SlotsDoBetFreeReq) GetGameStorage() []*GameStorageItem {
	if x != nil {
		return x.GameStorage
	}
	return nil
}

func (x *SlotsDoBetFreeReq) GetFlowControl() *SlotDoBetFlowControl {
	if x != nil {
		return x.FlowControl
	}
	return nil
}

type SlotsDoBetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Ret           bool                   `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyCent  int64                  `protobuf:"varint,4,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsDoBetResp) Reset() {
	*x = SlotsDoBetResp{}
	mi := &file_lottery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsDoBetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsDoBetResp) ProtoMessage() {}

func (x *SlotsDoBetResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsDoBetResp.ProtoReflect.Descriptor instead.
func (*SlotsDoBetResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{14}
}

func (x *SlotsDoBetResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SlotsDoBetResp) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *SlotsDoBetResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SlotsDoBetResp) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

func (x *SlotsDoBetResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FruitDoBetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId       uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId        uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	BetAmount     string                 `protobuf:"bytes,6,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	WinAmount     string                 `protobuf:"bytes,7,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
	RecordJson    string                 `protobuf:"bytes,8,opt,name=recordJson,proto3" json:"recordJson,omitempty"`
	Complete      bool                   `protobuf:"varint,9,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitDoBetReq) Reset() {
	*x = FruitDoBetReq{}
	mi := &file_lottery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitDoBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitDoBetReq) ProtoMessage() {}

func (x *FruitDoBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitDoBetReq.ProtoReflect.Descriptor instead.
func (*FruitDoBetReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{15}
}

func (x *FruitDoBetReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FruitDoBetReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *FruitDoBetReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *FruitDoBetReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *FruitDoBetReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *FruitDoBetReq) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *FruitDoBetReq) GetWinAmount() string {
	if x != nil {
		return x.WinAmount
	}
	return ""
}

func (x *FruitDoBetReq) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

func (x *FruitDoBetReq) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type FruitDoBetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Ret           bool                   `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyCent  int64                  `protobuf:"varint,4,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitDoBetResp) Reset() {
	*x = FruitDoBetResp{}
	mi := &file_lottery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitDoBetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitDoBetResp) ProtoMessage() {}

func (x *FruitDoBetResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitDoBetResp.ProtoReflect.Descriptor instead.
func (*FruitDoBetResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{16}
}

func (x *FruitDoBetResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *FruitDoBetResp) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *FruitDoBetResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FruitDoBetResp) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

type FruitDoBetMultiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId       uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId        uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	BetAmount     string                 `protobuf:"bytes,6,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	AreaId        uint32                 `protobuf:"varint,7,opt,name=areaId,proto3" json:"areaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitDoBetMultiReq) Reset() {
	*x = FruitDoBetMultiReq{}
	mi := &file_lottery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitDoBetMultiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitDoBetMultiReq) ProtoMessage() {}

func (x *FruitDoBetMultiReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitDoBetMultiReq.ProtoReflect.Descriptor instead.
func (*FruitDoBetMultiReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{17}
}

func (x *FruitDoBetMultiReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FruitDoBetMultiReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *FruitDoBetMultiReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *FruitDoBetMultiReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *FruitDoBetMultiReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *FruitDoBetMultiReq) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

func (x *FruitDoBetMultiReq) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

type FruitDoBetMultiResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Ret           bool                   `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyCent  int64                  `protobuf:"varint,4,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitDoBetMultiResp) Reset() {
	*x = FruitDoBetMultiResp{}
	mi := &file_lottery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitDoBetMultiResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitDoBetMultiResp) ProtoMessage() {}

func (x *FruitDoBetMultiResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitDoBetMultiResp.ProtoReflect.Descriptor instead.
func (*FruitDoBetMultiResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{18}
}

func (x *FruitDoBetMultiResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *FruitDoBetMultiResp) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *FruitDoBetMultiResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FruitDoBetMultiResp) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

type FruitRefundMultiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId       uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	GameId        uint32                 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	BetAmount     string                 `protobuf:"bytes,6,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitRefundMultiReq) Reset() {
	*x = FruitRefundMultiReq{}
	mi := &file_lottery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitRefundMultiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitRefundMultiReq) ProtoMessage() {}

func (x *FruitRefundMultiReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitRefundMultiReq.ProtoReflect.Descriptor instead.
func (*FruitRefundMultiReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{19}
}

func (x *FruitRefundMultiReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FruitRefundMultiReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *FruitRefundMultiReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *FruitRefundMultiReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *FruitRefundMultiReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *FruitRefundMultiReq) GetBetAmount() string {
	if x != nil {
		return x.BetAmount
	}
	return ""
}

type FruitRefundMultiResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Ret           bool                   `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyCent  int64                  `protobuf:"varint,4,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitRefundMultiResp) Reset() {
	*x = FruitRefundMultiResp{}
	mi := &file_lottery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitRefundMultiResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitRefundMultiResp) ProtoMessage() {}

func (x *FruitRefundMultiResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitRefundMultiResp.ProtoReflect.Descriptor instead.
func (*FruitRefundMultiResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{20}
}

func (x *FruitRefundMultiResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *FruitRefundMultiResp) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *FruitRefundMultiResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FruitRefundMultiResp) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

type FruitSettlePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserIcon      int32                  `protobuf:"varint,3,opt,name=userIcon,proto3" json:"userIcon,omitempty"`
	TotalBet      string                 `protobuf:"bytes,4,opt,name=totalBet,proto3" json:"totalBet,omitempty"`
	WinAmount     string                 `protobuf:"bytes,5,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
	RecordJson    string                 `protobuf:"bytes,6,opt,name=recordJson,proto3" json:"recordJson,omitempty"`
	Account       string                 `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitSettlePlayer) Reset() {
	*x = FruitSettlePlayer{}
	mi := &file_lottery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitSettlePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitSettlePlayer) ProtoMessage() {}

func (x *FruitSettlePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitSettlePlayer.ProtoReflect.Descriptor instead.
func (*FruitSettlePlayer) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{21}
}

func (x *FruitSettlePlayer) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FruitSettlePlayer) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FruitSettlePlayer) GetUserIcon() int32 {
	if x != nil {
		return x.UserIcon
	}
	return 0
}

func (x *FruitSettlePlayer) GetTotalBet() string {
	if x != nil {
		return x.TotalBet
	}
	return ""
}

func (x *FruitSettlePlayer) GetWinAmount() string {
	if x != nil {
		return x.WinAmount
	}
	return ""
}

func (x *FruitSettlePlayer) GetRecordJson() string {
	if x != nil {
		return x.RecordJson
	}
	return ""
}

func (x *FruitSettlePlayer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type FruitSettleRoundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        uint32                 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AgentId       uint32                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,3,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	Period        int64                  `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	RoundId       string                 `protobuf:"bytes,5,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Players       []*FruitSettlePlayer   `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitSettleRoundReq) Reset() {
	*x = FruitSettleRoundReq{}
	mi := &file_lottery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitSettleRoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitSettleRoundReq) ProtoMessage() {}

func (x *FruitSettleRoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitSettleRoundReq.ProtoReflect.Descriptor instead.
func (*FruitSettleRoundReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{22}
}

func (x *FruitSettleRoundReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *FruitSettleRoundReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *FruitSettleRoundReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *FruitSettleRoundReq) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *FruitSettleRoundReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *FruitSettleRoundReq) GetPlayers() []*FruitSettlePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type FruitSettlePlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencyCent  int64                  `protobuf:"varint,3,opt,name=currencyCent,proto3" json:"currencyCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitSettlePlayerResult) Reset() {
	*x = FruitSettlePlayerResult{}
	mi := &file_lottery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitSettlePlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitSettlePlayerResult) ProtoMessage() {}

func (x *FruitSettlePlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitSettlePlayerResult.ProtoReflect.Descriptor instead.
func (*FruitSettlePlayerResult) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{23}
}

func (x *FruitSettlePlayerResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FruitSettlePlayerResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FruitSettlePlayerResult) GetCurrencyCent() int64 {
	if x != nil {
		return x.CurrencyCent
	}
	return 0
}

type FruitSettleRoundResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          ErrorCode                  `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Ret           bool                       `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Players       []*FruitSettlePlayerResult `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitSettleRoundResp) Reset() {
	*x = FruitSettleRoundResp{}
	mi := &file_lottery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitSettleRoundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitSettleRoundResp) ProtoMessage() {}

func (x *FruitSettleRoundResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitSettleRoundResp.ProtoReflect.Descriptor instead.
func (*FruitSettleRoundResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{24}
}

func (x *FruitSettleRoundResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *FruitSettleRoundResp) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *FruitSettleRoundResp) GetPlayers() []*FruitSettlePlayerResult {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_lottery_proto protoreflect.FileDescriptor

const file_lottery_proto_rawDesc = "" +
	"\n" +
	"\rlottery.proto\x12\alottery\x1a\n" +
	"base.proto\"k\n" +
	"\x13PoolAmountResultReq\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\"X\n" +
	"\x14PoolAmountResultResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"'\n" +
	"\rGetBalanceReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"v\n" +
	"\x0eGetBalanceResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x03 \x01(\x03R\fcurrencyCent\"\xcc\x01\n" +
	"\x12SaveGameStorageReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\rR\x06gameId\x12&\n" +
	"\x0ecurrencySymbol\x18\x03 \x01(\tR\x0ecurrencySymbol\x12\x1e\n" +
	"\n" +
	"storageKey\x18\x04 \x01(\tR\n" +
	"storageKey\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12$\n" +
	"\rexpireSeconds\x18\x06 \x01(\x03R\rexpireSeconds\";\n" +
	"\x13SaveGameStorageResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"\x8c\x01\n" +
	"\x12LoadGameStorageReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\rR\x06gameId\x12&\n" +
	"\x0ecurrencySymbol\x18\x03 \x01(\tR\x0ecurrencySymbol\x12\x1e\n" +
	"\n" +
	"storageKey\x18\x04 \x01(\tR\n" +
	"storageKey\"k\n" +
	"\x13LoadGameStorageResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\x8e\x01\n" +
	"\x14DeleteGameStorageReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06gameId\x18\x02 \x01(\rR\x06gameId\x12&\n" +
	"\x0ecurrencySymbol\x18\x03 \x01(\tR\x0ecurrencySymbol\x12\x1e\n" +
	"\n" +
	"storageKey\x18\x04 \x01(\tR\n" +
	"storageKey\"=\n" +
	"\x15DeleteGameStorageResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"q\n" +
	"\x0fGameStorageItem\x12\x1e\n" +
	"\n" +
	"storageKey\x18\x01 \x01(\tR\n" +
	"storageKey\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12$\n" +
	"\rexpireSeconds\x18\x03 \x01(\x03R\rexpireSeconds\"x\n" +
	"\x14SlotDoBetFlowControl\x12*\n" +
	"\x10refundPoolAmount\x18\x01 \x01(\tR\x10refundPoolAmount\x124\n" +
	"\x15deleteGameStorageKeys\x18\x02 \x03(\tR\x15deleteGameStorageKeys\"\xae\x03\n" +
	"\rSlotsDoBetReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x1c\n" +
	"\tbetAmount\x18\x06 \x01(\tR\tbetAmount\x12\x1c\n" +
	"\twinAmount\x18\a \x01(\tR\twinAmount\x12\"\n" +
	"\fpreWinAmount\x18\b \x01(\tR\fpreWinAmount\x12\x18\n" +
	"\aaccount\x18\t \x01(\tR\aaccount\x12\x1e\n" +
	"\n" +
	"recordJson\x18\n" +
	" \x01(\tR\n" +
	"recordJson\x12:\n" +
	"\vgameStorage\x18\v \x03(\v2\x18.lottery.GameStorageItemR\vgameStorage\x12?\n" +
	"\vflowControl\x18\f \x01(\v2\x1d.lottery.SlotDoBetFlowControlR\vflowControl\"\xb4\x03\n" +
	"\x11SlotsDoBetFreeReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x1c\n" +
	"\twinAmount\x18\x06 \x01(\tR\twinAmount\x12\x18\n" +
	"\aaccount\x18\a \x01(\tR\aaccount\x12\x1e\n" +
	"\n" +
	"recordJson\x18\b \x01(\tR\n" +
	"recordJson\x12&\n" +
	"\x0etotalBetAmount\x18\t \x01(\tR\x0etotalBetAmount\x12\x1a\n" +
	"\bcomplete\x18\n" +
	" \x01(\bR\bcomplete\x12:\n" +
	"\vgameStorage\x18\v \x03(\v2\x18.lottery.GameStorageItemR\vgameStorage\x12?\n" +
	"\vflowControl\x18\f \x01(\v2\x1d.lottery.SlotDoBetFlowControlR\vflowControl\"\x9e\x01\n" +
	"\x0eSlotsDoBetResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\bR\x03ret\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x04 \x01(\x03R\fcurrencyCent\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8f\x02\n" +
	"\rFruitDoBetReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x1c\n" +
	"\tbetAmount\x18\x06 \x01(\tR\tbetAmount\x12\x1c\n" +
	"\twinAmount\x18\a \x01(\tR\twinAmount\x12\x1e\n" +
	"\n" +
	"recordJson\x18\b \x01(\tR\n" +
	"recordJson\x12\x1a\n" +
	"\bcomplete\x18\t \x01(\bR\bcomplete\"\x88\x01\n" +
	"\x0eFruitDoBetResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\bR\x03ret\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x04 \x01(\x03R\fcurrencyCent\"\xd2\x01\n" +
	"\x12FruitDoBetMultiReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x1c\n" +
	"\tbetAmount\x18\x06 \x01(\tR\tbetAmount\x12\x16\n" +
	"\x06areaId\x18\a \x01(\rR\x06areaId\"\x8d\x01\n" +
	"\x13FruitDoBetMultiResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\bR\x03ret\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x04 \x01(\x03R\fcurrencyCent\"\xbb\x01\n" +
	"\x13FruitRefundMultiReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\x16\n" +
	"\x06gameId\x18\x03 \x01(\rR\x06gameId\x12\"\n" +
	"\fcurrencyType\x18\x04 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x12\x1c\n" +
	"\tbetAmount\x18\x06 \x01(\tR\tbetAmount\"\x8e\x01\n" +
	"\x14FruitRefundMultiResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\bR\x03ret\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x04 \x01(\x03R\fcurrencyCent\"\xd7\x01\n" +
	"\x11FruitSettlePlayer\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\buserIcon\x18\x03 \x01(\x05R\buserIcon\x12\x1a\n" +
	"\btotalBet\x18\x04 \x01(\tR\btotalBet\x12\x1c\n" +
	"\twinAmount\x18\x05 \x01(\tR\twinAmount\x12\x1e\n" +
	"\n" +
	"recordJson\x18\x06 \x01(\tR\n" +
	"recordJson\x12\x18\n" +
	"\aaccount\x18\a \x01(\tR\aaccount\"\xd3\x01\n" +
	"\x13FruitSettleRoundReq\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\rR\x06gameId\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\rR\aagentId\x12\"\n" +
	"\fcurrencyType\x18\x03 \x01(\tR\fcurrencyType\x12\x16\n" +
	"\x06period\x18\x04 \x01(\x03R\x06period\x12\x18\n" +
	"\aroundId\x18\x05 \x01(\tR\aroundId\x124\n" +
	"\aplayers\x18\x06 \x03(\v2\x1a.lottery.FruitSettlePlayerR\aplayers\"q\n" +
	"\x17FruitSettlePlayerResult\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\"\n" +
	"\fcurrencyCent\x18\x03 \x01(\x03R\fcurrencyCent\"\x8a\x01\n" +
	"\x14FruitSettleRoundResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\bR\x03ret\x12:\n" +
	"\aplayers\x18\x03 \x03(\v2 .lottery.FruitSettlePlayerResultR\aplayers2\xc5\x06\n" +
	"\x0eLotteryService\x12O\n" +
	"\x10PoolAmountResult\x12\x1c.lottery.PoolAmountResultReq\x1a\x1d.lottery.PoolAmountResultResp\x12=\n" +
	"\n" +
	"GetBalance\x12\x16.lottery.GetBalanceReq\x1a\x17.lottery.GetBalanceResp\x12L\n" +
	"\x0fSaveGameStorage\x12\x1b.lottery.SaveGameStorageReq\x1a\x1c.lottery.SaveGameStorageResp\x12L\n" +
	"\x0fLoadGameStorage\x12\x1b.lottery.LoadGameStorageReq\x1a\x1c.lottery.LoadGameStorageResp\x12R\n" +
	"\x11DeleteGameStorage\x12\x1d.lottery.DeleteGameStorageReq\x1a\x1e.lottery.DeleteGameStorageResp\x12=\n" +
	"\n" +
	"SlotsDoBet\x12\x16.lottery.SlotsDoBetReq\x1a\x17.lottery.SlotsDoBetResp\x12E\n" +
	"\x0eSlotsDoBetFree\x12\x1a.lottery.SlotsDoBetFreeReq\x1a\x17.lottery.SlotsDoBetResp\x12=\n" +
	"\n" +
	"FruitDoBet\x12\x16.lottery.FruitDoBetReq\x1a\x17.lottery.FruitDoBetResp\x12L\n" +
	"\x0fFruitDoBetMulti\x12\x1b.lottery.FruitDoBetMultiReq\x1a\x1c.lottery.FruitDoBetMultiResp\x12O\n" +
	"\x10FruitRefundMulti\x12\x1c.lottery.FruitRefundMultiReq\x1a\x1d.lottery.FruitRefundMultiResp\x12O\n" +
	"\x10FruitSettleRound\x12\x1c.lottery.FruitSettleRoundReq\x1a\x1d.lottery.FruitSettleRoundRespB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_lottery_proto_rawDescOnce sync.Once
	file_lottery_proto_rawDescData []byte
)

func file_lottery_proto_rawDescGZIP() []byte {
	file_lottery_proto_rawDescOnce.Do(func() {
		file_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)))
	})
	return file_lottery_proto_rawDescData
}

var file_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_lottery_proto_goTypes = []any{
	(*PoolAmountResultReq)(nil),     // 0: lottery.PoolAmountResultReq
	(*PoolAmountResultResp)(nil),    // 1: lottery.PoolAmountResultResp
	(*GetBalanceReq)(nil),           // 2: lottery.GetBalanceReq
	(*GetBalanceResp)(nil),          // 3: lottery.GetBalanceResp
	(*SaveGameStorageReq)(nil),      // 4: lottery.SaveGameStorageReq
	(*SaveGameStorageResp)(nil),     // 5: lottery.SaveGameStorageResp
	(*LoadGameStorageReq)(nil),      // 6: lottery.LoadGameStorageReq
	(*LoadGameStorageResp)(nil),     // 7: lottery.LoadGameStorageResp
	(*DeleteGameStorageReq)(nil),    // 8: lottery.DeleteGameStorageReq
	(*DeleteGameStorageResp)(nil),   // 9: lottery.DeleteGameStorageResp
	(*GameStorageItem)(nil),         // 10: lottery.GameStorageItem
	(*SlotDoBetFlowControl)(nil),    // 11: lottery.SlotDoBetFlowControl
	(*SlotsDoBetReq)(nil),           // 12: lottery.SlotsDoBetReq
	(*SlotsDoBetFreeReq)(nil),       // 13: lottery.SlotsDoBetFreeReq
	(*SlotsDoBetResp)(nil),          // 14: lottery.SlotsDoBetResp
	(*FruitDoBetReq)(nil),           // 15: lottery.FruitDoBetReq
	(*FruitDoBetResp)(nil),          // 16: lottery.FruitDoBetResp
	(*FruitDoBetMultiReq)(nil),      // 17: lottery.FruitDoBetMultiReq
	(*FruitDoBetMultiResp)(nil),     // 18: lottery.FruitDoBetMultiResp
	(*FruitRefundMultiReq)(nil),     // 19: lottery.FruitRefundMultiReq
	(*FruitRefundMultiResp)(nil),    // 20: lottery.FruitRefundMultiResp
	(*FruitSettlePlayer)(nil),       // 21: lottery.FruitSettlePlayer
	(*FruitSettleRoundReq)(nil),     // 22: lottery.FruitSettleRoundReq
	(*FruitSettlePlayerResult)(nil), // 23: lottery.FruitSettlePlayerResult
	(*FruitSettleRoundResp)(nil),    // 24: lottery.FruitSettleRoundResp
	(ErrorCode)(0),                  // 25: base.error_code
}
var file_lottery_proto_depIdxs = []int32{
	25, // 0: lottery.PoolAmountResultResp.code:type_name -> base.error_code
	25, // 1: lottery.GetBalanceResp.code:type_name -> base.error_code
	25, // 2: lottery.SaveGameStorageResp.code:type_name -> base.error_code
	25, // 3: lottery.LoadGameStorageResp.code:type_name -> base.error_code
	25, // 4: lottery.DeleteGameStorageResp.code:type_name -> base.error_code
	10, // 5: lottery.SlotsDoBetReq.gameStorage:type_name -> lottery.GameStorageItem
	11, // 6: lottery.SlotsDoBetReq.flowControl:type_name -> lottery.SlotDoBetFlowControl
	10, // 7: lottery.SlotsDoBetFreeReq.gameStorage:type_name -> lottery.GameStorageItem
	11, // 8: lottery.SlotsDoBetFreeReq.flowControl:type_name -> lottery.SlotDoBetFlowControl
	25, // 9: lottery.SlotsDoBetResp.code:type_name -> base.error_code
	25, // 10: lottery.FruitDoBetResp.code:type_name -> base.error_code
	25, // 11: lottery.FruitDoBetMultiResp.code:type_name -> base.error_code
	25, // 12: lottery.FruitRefundMultiResp.code:type_name -> base.error_code
	21, // 13: lottery.FruitSettleRoundReq.players:type_name -> lottery.FruitSettlePlayer
	25, // 14: lottery.FruitSettleRoundResp.code:type_name -> base.error_code
	23, // 15: lottery.FruitSettleRoundResp.players:type_name -> lottery.FruitSettlePlayerResult
	0,  // 16: lottery.LotteryService.PoolAmountResult:input_type -> lottery.PoolAmountResultReq
	2,  // 17: lottery.LotteryService.GetBalance:input_type -> lottery.GetBalanceReq
	4,  // 18: lottery.LotteryService.SaveGameStorage:input_type -> lottery.SaveGameStorageReq
	6,  // 19: lottery.LotteryService.LoadGameStorage:input_type -> lottery.LoadGameStorageReq
	8,  // 20: lottery.LotteryService.DeleteGameStorage:input_type -> lottery.DeleteGameStorageReq
	12, // 21: lottery.LotteryService.SlotsDoBet:input_type -> lottery.SlotsDoBetReq
	13, // 22: lottery.LotteryService.SlotsDoBetFree:input_type -> lottery.SlotsDoBetFreeReq
	15, // 23: lottery.LotteryService.FruitDoBet:input_type -> lottery.FruitDoBetReq
	17, // 24: lottery.LotteryService.FruitDoBetMulti:input_type -> lottery.FruitDoBetMultiReq
	19, // 25: lottery.LotteryService.FruitRefundMulti:input_type -> lottery.FruitRefundMultiReq
	22, // 26: lottery.LotteryService.FruitSettleRound:input_type -> lottery.FruitSettleRoundReq
	1,  // 27: lottery.LotteryService.PoolAmountResult:output_type -> lottery.PoolAmountResultResp
	3,  // 28: lottery.LotteryService.GetBalance:output_type -> lottery.GetBalanceResp
	5,  // 29: lottery.LotteryService.SaveGameStorage:output_type -> lottery.SaveGameStorageResp
	7,  // 30: lottery.LotteryService.LoadGameStorage:output_type -> lottery.LoadGameStorageResp
	9,  // 31: lottery.LotteryService.DeleteGameStorage:output_type -> lottery.DeleteGameStorageResp
	14, // 32: lottery.LotteryService.SlotsDoBet:output_type -> lottery.SlotsDoBetResp
	14, // 33: lottery.LotteryService.SlotsDoBetFree:output_type -> lottery.SlotsDoBetResp
	16, // 34: lottery.LotteryService.FruitDoBet:output_type -> lottery.FruitDoBetResp
	18, // 35: lottery.LotteryService.FruitDoBetMulti:output_type -> lottery.FruitDoBetMultiResp
	20, // 36: lottery.LotteryService.FruitRefundMulti:output_type -> lottery.FruitRefundMultiResp
	24, // 37: lottery.LotteryService.FruitSettleRound:output_type -> lottery.FruitSettleRoundResp
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_lottery_proto_init() }
func file_lottery_proto_init() {
	if File_lottery_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_proto_depIdxs,
		MessageInfos:      file_lottery_proto_msgTypes,
	}.Build()
	File_lottery_proto = out.File
	file_lottery_proto_goTypes = nil
	file_lottery_proto_depIdxs = nil
}
