// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: lottery.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryService_PoolAmountResult_FullMethodName  = "/lottery.LotteryService/PoolAmountResult"
	LotteryService_GetBalance_FullMethodName        = "/lottery.LotteryService/GetBalance"
	LotteryService_SaveGameStorage_FullMethodName   = "/lottery.LotteryService/SaveGameStorage"
	LotteryService_LoadGameStorage_FullMethodName   = "/lottery.LotteryService/LoadGameStorage"
	LotteryService_DeleteGameStorage_FullMethodName = "/lottery.LotteryService/DeleteGameStorage"
	LotteryService_SlotsDoBet_FullMethodName        = "/lottery.LotteryService/SlotsDoBet"
	LotteryService_SlotsDoBetFree_FullMethodName    = "/lottery.LotteryService/SlotsDoBetFree"
	LotteryService_FruitDoBet_FullMethodName        = "/lottery.LotteryService/FruitDoBet"
	LotteryService_FruitDoBetMulti_FullMethodName   = "/lottery.LotteryService/FruitDoBetMulti"
	LotteryService_FruitRefundMulti_FullMethodName  = "/lottery.LotteryService/FruitRefundMulti"
	LotteryService_FruitSettleRound_FullMethodName  = "/lottery.LotteryService/FruitSettleRound"
)

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryServiceClient interface {
	// 获取水池数据
	PoolAmountResult(ctx context.Context, in *PoolAmountResultReq, opts ...grpc.CallOption) (*PoolAmountResultResp, error)
	// 权威余额查询（供 CommonRpcProd.getBalance）
	GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
	// 长期游戏状态存储（供 StorageRpcProd，落库不走注单链路）
	SaveGameStorage(ctx context.Context, in *SaveGameStorageReq, opts ...grpc.CallOption) (*SaveGameStorageResp, error)
	LoadGameStorage(ctx context.Context, in *LoadGameStorageReq, opts ...grpc.CallOption) (*LoadGameStorageResp, error)
	DeleteGameStorage(ctx context.Context, in *DeleteGameStorageReq, opts ...grpc.CallOption) (*DeleteGameStorageResp, error)
	// 新服正式环境门面
	SlotsDoBet(ctx context.Context, in *SlotsDoBetReq, opts ...grpc.CallOption) (*SlotsDoBetResp, error)
	SlotsDoBetFree(ctx context.Context, in *SlotsDoBetFreeReq, opts ...grpc.CallOption) (*SlotsDoBetResp, error)
	FruitDoBet(ctx context.Context, in *FruitDoBetReq, opts ...grpc.CallOption) (*FruitDoBetResp, error)
	FruitDoBetMulti(ctx context.Context, in *FruitDoBetMultiReq, opts ...grpc.CallOption) (*FruitDoBetMultiResp, error)
	FruitRefundMulti(ctx context.Context, in *FruitRefundMultiReq, opts ...grpc.CallOption) (*FruitRefundMultiResp, error)
	FruitSettleRound(ctx context.Context, in *FruitSettleRoundReq, opts ...grpc.CallOption) (*FruitSettleRoundResp, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) PoolAmountResult(ctx context.Context, in *PoolAmountResultReq, opts ...grpc.CallOption) (*PoolAmountResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolAmountResultResp)
	err := c.cc.Invoke(ctx, LotteryService_PoolAmountResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResp)
	err := c.cc.Invoke(ctx, LotteryService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) SaveGameStorage(ctx context.Context, in *SaveGameStorageReq, opts ...grpc.CallOption) (*SaveGameStorageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGameStorageResp)
	err := c.cc.Invoke(ctx, LotteryService_SaveGameStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) LoadGameStorage(ctx context.Context, in *LoadGameStorageReq, opts ...grpc.CallOption) (*LoadGameStorageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadGameStorageResp)
	err := c.cc.Invoke(ctx, LotteryService_LoadGameStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) DeleteGameStorage(ctx context.Context, in *DeleteGameStorageReq, opts ...grpc.CallOption) (*DeleteGameStorageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGameStorageResp)
	err := c.cc.Invoke(ctx, LotteryService_DeleteGameStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) SlotsDoBet(ctx context.Context, in *SlotsDoBetReq, opts ...grpc.CallOption) (*SlotsDoBetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotsDoBetResp)
	err := c.cc.Invoke(ctx, LotteryService_SlotsDoBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) SlotsDoBetFree(ctx context.Context, in *SlotsDoBetFreeReq, opts ...grpc.CallOption) (*SlotsDoBetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotsDoBetResp)
	err := c.cc.Invoke(ctx, LotteryService_SlotsDoBetFree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) FruitDoBet(ctx context.Context, in *FruitDoBetReq, opts ...grpc.CallOption) (*FruitDoBetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FruitDoBetResp)
	err := c.cc.Invoke(ctx, LotteryService_FruitDoBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) FruitDoBetMulti(ctx context.Context, in *FruitDoBetMultiReq, opts ...grpc.CallOption) (*FruitDoBetMultiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FruitDoBetMultiResp)
	err := c.cc.Invoke(ctx, LotteryService_FruitDoBetMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) FruitRefundMulti(ctx context.Context, in *FruitRefundMultiReq, opts ...grpc.CallOption) (*FruitRefundMultiResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FruitRefundMultiResp)
	err := c.cc.Invoke(ctx, LotteryService_FruitRefundMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) FruitSettleRound(ctx context.Context, in *FruitSettleRoundReq, opts ...grpc.CallOption) (*FruitSettleRoundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FruitSettleRoundResp)
	err := c.cc.Invoke(ctx, LotteryService_FruitSettleRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
// All implementations must embed UnimplementedLotteryServiceServer
// for forward compatibility.
type LotteryServiceServer interface {
	// 获取水池数据
	PoolAmountResult(context.Context, *PoolAmountResultReq) (*PoolAmountResultResp, error)
	// 权威余额查询（供 CommonRpcProd.getBalance）
	GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error)
	// 长期游戏状态存储（供 StorageRpcProd，落库不走注单链路）
	SaveGameStorage(context.Context, *SaveGameStorageReq) (*SaveGameStorageResp, error)
	LoadGameStorage(context.Context, *LoadGameStorageReq) (*LoadGameStorageResp, error)
	DeleteGameStorage(context.Context, *DeleteGameStorageReq) (*DeleteGameStorageResp, error)
	// 新服正式环境门面
	SlotsDoBet(context.Context, *SlotsDoBetReq) (*SlotsDoBetResp, error)
	SlotsDoBetFree(context.Context, *SlotsDoBetFreeReq) (*SlotsDoBetResp, error)
	FruitDoBet(context.Context, *FruitDoBetReq) (*FruitDoBetResp, error)
	FruitDoBetMulti(context.Context, *FruitDoBetMultiReq) (*FruitDoBetMultiResp, error)
	FruitRefundMulti(context.Context, *FruitRefundMultiReq) (*FruitRefundMultiResp, error)
	FruitSettleRound(context.Context, *FruitSettleRoundReq) (*FruitSettleRoundResp, error)
	mustEmbedUnimplementedLotteryServiceServer()
}

// UnimplementedLotteryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServiceServer struct{}

func (UnimplementedLotteryServiceServer) PoolAmountResult(context.Context, *PoolAmountResultReq) (*PoolAmountResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PoolAmountResult not implemented")
}
func (UnimplementedLotteryServiceServer) GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedLotteryServiceServer) SaveGameStorage(context.Context, *SaveGameStorageReq) (*SaveGameStorageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveGameStorage not implemented")
}
func (UnimplementedLotteryServiceServer) LoadGameStorage(context.Context, *LoadGameStorageReq) (*LoadGameStorageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadGameStorage not implemented")
}
func (UnimplementedLotteryServiceServer) DeleteGameStorage(context.Context, *DeleteGameStorageReq) (*DeleteGameStorageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGameStorage not implemented")
}
func (UnimplementedLotteryServiceServer) SlotsDoBet(context.Context, *SlotsDoBetReq) (*SlotsDoBetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SlotsDoBet not implemented")
}
func (UnimplementedLotteryServiceServer) SlotsDoBetFree(context.Context, *SlotsDoBetFreeReq) (*SlotsDoBetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SlotsDoBetFree not implemented")
}
func (UnimplementedLotteryServiceServer) FruitDoBet(context.Context, *FruitDoBetReq) (*FruitDoBetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FruitDoBet not implemented")
}
func (UnimplementedLotteryServiceServer) FruitDoBetMulti(context.Context, *FruitDoBetMultiReq) (*FruitDoBetMultiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FruitDoBetMulti not implemented")
}
func (UnimplementedLotteryServiceServer) FruitRefundMulti(context.Context, *FruitRefundMultiReq) (*FruitRefundMultiResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FruitRefundMulti not implemented")
}
func (UnimplementedLotteryServiceServer) FruitSettleRound(context.Context, *FruitSettleRoundReq) (*FruitSettleRoundResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FruitSettleRound not implemented")
}
func (UnimplementedLotteryServiceServer) mustEmbedUnimplementedLotteryServiceServer() {}
func (UnimplementedLotteryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotteryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServiceServer will
// result in compilation errors.
type UnsafeLotteryServiceServer interface {
	mustEmbedUnimplementedLotteryServiceServer()
}

func RegisterLotteryServiceServer(s grpc.ServiceRegistrar, srv LotteryServiceServer) {
	// If the following call panics, it indicates UnimplementedLotteryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryService_ServiceDesc, srv)
}

func _LotteryService_PoolAmountResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolAmountResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).PoolAmountResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_PoolAmountResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).PoolAmountResult(ctx, req.(*PoolAmountResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetBalance(ctx, req.(*GetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_SaveGameStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGameStorageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).SaveGameStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_SaveGameStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).SaveGameStorage(ctx, req.(*SaveGameStorageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_LoadGameStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGameStorageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).LoadGameStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_LoadGameStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).LoadGameStorage(ctx, req.(*LoadGameStorageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_DeleteGameStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameStorageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).DeleteGameStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_DeleteGameStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).DeleteGameStorage(ctx, req.(*DeleteGameStorageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_SlotsDoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsDoBetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).SlotsDoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_SlotsDoBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).SlotsDoBet(ctx, req.(*SlotsDoBetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_SlotsDoBetFree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsDoBetFreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).SlotsDoBetFree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_SlotsDoBetFree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).SlotsDoBetFree(ctx, req.(*SlotsDoBetFreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_FruitDoBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FruitDoBetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).FruitDoBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_FruitDoBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).FruitDoBet(ctx, req.(*FruitDoBetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_FruitDoBetMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FruitDoBetMultiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).FruitDoBetMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_FruitDoBetMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).FruitDoBetMulti(ctx, req.(*FruitDoBetMultiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_FruitRefundMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FruitRefundMultiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).FruitRefundMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_FruitRefundMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).FruitRefundMulti(ctx, req.(*FruitRefundMultiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_FruitSettleRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FruitSettleRoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).FruitSettleRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_FruitSettleRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).FruitSettleRound(ctx, req.(*FruitSettleRoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LotteryService_ServiceDesc is the grpc.ServiceDesc for LotteryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PoolAmountResult",
			Handler:    _LotteryService_PoolAmountResult_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _LotteryService_GetBalance_Handler,
		},
		{
			MethodName: "SaveGameStorage",
			Handler:    _LotteryService_SaveGameStorage_Handler,
		},
		{
			MethodName: "LoadGameStorage",
			Handler:    _LotteryService_LoadGameStorage_Handler,
		},
		{
			MethodName: "DeleteGameStorage",
			Handler:    _LotteryService_DeleteGameStorage_Handler,
		},
		{
			MethodName: "SlotsDoBet",
			Handler:    _LotteryService_SlotsDoBet_Handler,
		},
		{
			MethodName: "SlotsDoBetFree",
			Handler:    _LotteryService_SlotsDoBetFree_Handler,
		},
		{
			MethodName: "FruitDoBet",
			Handler:    _LotteryService_FruitDoBet_Handler,
		},
		{
			MethodName: "FruitDoBetMulti",
			Handler:    _LotteryService_FruitDoBetMulti_Handler,
		},
		{
			MethodName: "FruitRefundMulti",
			Handler:    _LotteryService_FruitRefundMulti_Handler,
		},
		{
			MethodName: "FruitSettleRound",
			Handler:    _LotteryService_FruitSettleRound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
